spring.application.name=Mentora

# =====================
# SQL SERVER
# =====================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=mentora_db2;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ====================
# JPA / HIBERNATE
# =====================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================
# THYMELEAF
# =====================
spring.thymeleaf.cache=false

# =====================
# UPLOAD (node contents)
# =====================
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=210MB
mentora.upload.node-contents-dir=uploads/node-contents
